In [2]:
import cv2,matplotlib
import numpy as np
import matplotlib.pyplot as plt


In [2]:
imgg=cv2.imread("1.png")
print(imgg)

[[[ 86  89 193]
  [ 37  51 174]
  [ 39  50 192]
  ...
  [ 27  35 167]
  [ 27  35 163]
  [ 34  39 164]]

 [[ 44  58 176]
  [ 41  50 180]
  [ 40  49 192]
  ...
  [ 29  39 155]
  [ 28  38 155]
  [ 28  38 157]]

 [[ 43  55 187]
  [ 41  49 187]
  [ 41  49 193]
  ...
  [ 44  58 159]
  [ 30  45 152]
  [ 28  47 160]]

 ...

 [[131  97  80]
  [132  95  77]
  [129  94  75]
  ...
  [ 69  84  92]
  [ 63  77  78]
  [ 60  71  66]]

 [[107  74  48]
  [114  76  49]
  [110  74  45]
  ...
  [ 60  75  81]
  [ 53  69  70]
  [ 57  69  65]]

 [[ 96  65  46]
  [101  62  42]
  [ 98  61  39]
  ...
  [103 118 111]
  [ 81  99 104]
  [ 59  72  90]]]


In [3]:
import random

In [4]:
img=[]
for i in range(3):
  x=str(random.randint(1,35))
  img.append(cv2.imread(x+'.png'))
print(img)

[array([[[214, 176, 155],
        [228, 184, 162],
        [220, 174, 151],
        ...,
        [112,  87,  76],
        [103,  79,  68],
        [107,  83,  69]],

       [[191, 165, 147],
        [207, 175, 155],
        [200, 165, 143],
        ...,
        [ 88,  84,  75],
        [ 83,  79,  69],
        [ 82,  77,  66]],

       [[186, 155, 140],
        [201, 167, 149],
        [198, 162, 140],
        ...,
        [ 78,  74,  66],
        [ 70,  65,  56],
        [ 66,  59,  51]],

       ...,

       [[ 33,  29,  29],
        [ 32,  31,  31],
        [ 33,  31,  30],
        ...,
        [ 34,  30,  30],
        [ 36,  31,  31],
        [ 35,  29,  29]],

       [[ 35,  31,  32],
        [ 34,  30,  30],
        [ 33,  29,  29],
        ...,
        [ 36,  31,  31],
        [ 35,  30,  30],
        [ 34,  29,  29]],

       [[ 40,  35,  35],
        [ 38,  31,  30],
        [ 34,  28,  27],
        ...,
        [ 34,  28,  28],
        [ 34,  29,  29],
        [ 33,  29,  29]